# Docs:          https://www.conventionalcommits.org/en/v1.0.0/
# GitHub App:    https://github.com/zeke/semantic-pull-requests
# Configuration: https://github.com/zeke/semantic-pull-requests/blob/master/README.md#configuration

# Install the app onto the repository and set `enabled` to true.
enabled: false

# titleAndCommits: true
# commitsOnly: true
# titleOnly: true

# allowMergeCommits: true
# allowRevertCommits: true

types:
  - build    # Changes that affect the build system or external dependencies (example scopes: gulp, npm).
  - chore    # Other changes that don't modify src or test files.
  - ci       # Changes to CI configuration files and scripts (example scopes: Travis, GitHub Actions).
  - docs     # Documentation only changes.
  - feat     # A new feature.
  - fix      # A bug fix.
  - perf     # A code change that improves performance.
  - refactor # A code change that neither fixes a bug nor adds a feature.
  - revert   # Reverts a previous commit.
  - style    # Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc).
  - test     # Adding missing tests or correcting existing tests.
